version: "3.9"

services:
  langgraph:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    environment:
      - ENV=development
    command: poetry run python scripts/add_init_files.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langgraph
    ports:
      - "5432:5432"

# Add production-specific overrides for production
networks:
  default:
    external:
      name: my-network
